name = "Enchanced Craft"
author = "Ricky12Awesome"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "913846558e98c6289e079316720adfe7df0a0802c2efc03656e7583ed012193c"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
