name = "Enhanced Craft"
author = "Ricky12Awesome"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5334a17031ac11d5848803d876f4c85393c15dded7d864aff4435a301716596a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
