name = "BetterDarkMode"
filename = "betterdarkmode-1.0.5.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/f9nVUXRK/versions/1.0.5/betterdarkmode-1.0.5.jar"
hash-format = "sha1"
hash = "e5ac5341a4b55c76e7480e6bf8da0049be5bfcdd"

[update]
[update.modrinth]
mod-id = "f9nVUXRK"
version = "6zS1lWel"
