name = "Grid"
filename = "grid-1.18.2-fabric0.47.10-1.6.6.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/ebxDDOKt/versions/1.18.2-fabric0.47.10-1.6.6/grid-1.18.2-fabric0.47.10-1.6.6.jar"
hash-format = "sha1"
hash = "0b5c786c5ce2ed256acfef1b9bd9b6dbd88112aa"

[update]
[update.modrinth]
mod-id = "ebxDDOKt"
version = "k7EIHSq2"
