name = "MidnightLib"
filename = "midnightlib-0.4.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/codAaoxh/versions/0.4.0/midnightlib-0.4.0.jar"
hash-format = "sha1"
hash = "bad7a3239314c297a1793b96a8688ba71b0b928e"

[update]
[update.modrinth]
mod-id = "codAaoxh"
version = "enS8Fiz0"
