name = "RandomBlockPlacement"
filename = "randomblockplacement-1.18.2-fabric0.47.10-1.1.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/djlwpkGP/versions/1.18.2-fabric0.47.10-1.1.2/randomblockplacement-1.18.2-fabric0.47.10-1.1.2.jar"
hash-format = "sha1"
hash = "7699e7456daa23b70afdfda62c8ef1a3c8b81fad"

[update]
[update.modrinth]
mod-id = "djlwpkGP"
version = "vHNEWR0N"
