name = "TieFix"
filename = "TieFix-1.9.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/jxuxsA0D/versions/1.9.0/TieFix-1.9.0.jar"
hash-format = "sha1"
hash = "dc07b38ae4c4b4788851d852f51970d65103a01f"

[update]
[update.modrinth]
mod-id = "jxuxsA0D"
version = "7MP0Ay5i"
